SELECT * FROM TB_VENDAS

---=======TABELAS TEMPORARIAS============
--UTLIZA O INTO E O # PARA CRIAR A TABELA TAMPORIA

-- UTILIZANDO 1# SOMENTE É POSÍVEL CONSULTAR A TABELA TAMPORARIA NA MESMA SEÇÃO
SELECT * INTO #RELATORIO_LTZ FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ'

-- UTILIZANDO 2##  É POSÍVEL CONSULTAR A TABELA TAMPORARIA NA MESMA SEÇÃO E EM OUTRAS SEÇÕES
SELECT * INTO ##RELATORIO_LTZ FROM TB_VENDAS
WHERE VENDEDOR = 'LTZ'

SELECT * FROM #RELATORIO_LTZ