SELECT * FROM RELATORIO_NOVO
WHERE VENDEDOR = 'VIN'

--==================CRIAÇÃO DE VIEWS--=======================
CREATE VIEW VW_RELATORIO AS 
SELECT * FROM RELATORIO_NOVO
WHERE VENDEDOR = 'VIN'

SELECT * FROM VW_RELATORIO