
--=======================================
    --EXERCICIOS VIEWS + CRIAÇÃO DE TABELA
--=======================================

-- EXERCICIO 1
-- CRIAR UMA TABELA FISICA TRATANDO SO CAMPOS COM OS TIPOS DE DADOS

CREATE TABLE VENDAS_ATUALIZADA
(
	CUPOM INT,
	DATA  DATE,
	VENDEDOR VARCHAR(255),
	VALOR_VENDA DECIMAL(18,2)
)

INSERT INTO VENDAS_ATUALIZADA -- INSERT NO COMEÇO DA TABELA PRECISAMOS DE UMA TABELA JÁ CRIADA
SELECT
	CUPOM,
	DATA,
	VENDEDOR,
	VALOR_VENDA
FROM TB_VENDAS


--EXERCICIO 2
-- CRIAR UMA VIEW USANDO (SUM, FORMAT, BETWEEN e GROUP BY)

CREATE VIEW VW_VENDAS_ATUALIZADA AS
SELECT
	DATA,
	SUM(VALOR_VENDA) AS 'VALOR VENDAS',
	VENDEDOR,
	CUPOM
FROM VENDAS_ATUALIZADA
WHERE CUPOM BETWEEN 2 AND 30 	
GROUP BY DATA, VENDEDOR, CUPOM

SELECT * FROM VW_VENDAS_ATUALIZADA 

SELECT * FROM VENDAS_ATUALIZADA

