
--========TRATANDO OS ARQUIVOS--================


SELECT 
	RTRIM(NOME)            AS NOME,
	RTRIM(COD_CLI)         AS CLIENTE,
	RTRIM(ENDERECO)        AS ENDERECO,
	RTRIM(CPF)             AS CPF,
	RTRIM(CIDADE)          AS CIDADE,
	RTRIM(TIPO_DE_CLIENTE) AS PERFIL
FROM TB_CLIENTES

CREATE VIEW VW_RELATORIO_CLIENTE AS
SELECT 
	RTRIM(NOME)            AS NOME,
	RTRIM(COD_CLI)         AS CLIENTE,
	RTRIM(ENDERECO)        AS ENDERECO,
	RTRIM(CPF)             AS CPF,
	RTRIM(CIDADE)          AS CIDADE,
	RTRIM(TIPO_DE_CLIENTE) AS PERFIL
FROM TB_CLIENTES


SELECT * FROM VW_RELATORIO_CLIENTE



